# Generated by Django 4.2.7 on 2023-11-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='page.mydoctor')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_two_hours_notice', models.BooleanField(default=False)),
                ('is_one_day_notice', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='page.slot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='page.myuser')),
            ],
        ),
    ]
